Update aenetworks.py
Fixes:

[debug] Command-line config: ['-F', 'https://play.aetv.com/shows/neighborhood-wars', '-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.05.22 from yt-dlp/yt-dlp [7977b329e]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.2 (CPython AMD64 64bit) - Windows-10-10.0.18363-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 2025-05-01-git-707c04fe06-full_build-www.gyan.dev (setts), ffprobe 2025-05-01-git-707c04fe06-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.22.0, brotli-1.1.0, certifi-2025.04.26, curl_cffi-0.7.4 (unsupported), mutagen-1.47.0, requests-2.32.3, sqlite3-3.43.1, urllib3-1.26.20, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: none
[debug] Loaded 1860 extractors
[aenetworks:show] Extracting URL: https://play.aetv.com/shows/neighborhood-wars
ERROR: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1662, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1797, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\yt_dlp\extractor\common.py", line 748, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\yt_dlp\extractor\aenetworks.py", line 218, in _real_extract
    _, brand = self._DOMAIN_MAP[domain]
    ^^^^^^^^
ValueError: too many values to unpack (expected 2)

Also Fixes:
[debug] Command-line config: ['-F', 'https://play.aetv.com/shows/neighborhood-wars', '-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.05.22 from yt-dlp/yt-dlp [7977b329e] (pip)
[debug] Python 3.12.2 (CPython AMD64 64bit) - Windows-10-10.0.18363-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 2025-05-01-git-707c04fe06-full_build-www.gyan.dev (setts), ffprobe 2025-05-01-git-707c04fe06-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.29.0 (unsupported), sqlite3-3.43.1, urllib3-1.26.20, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets
[debug] Plugin directories: none
[debug] Loaded 1859 extractors
[aenetworks:show] Extracting URL: https://play.aetv.com/shows/neighborhood-wars
[aenetworks:show] neighborhood-wars: Downloading JSON metadata
ERROR: [aenetworks:show] neighborhood-wars: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\extractor\common.py", line 748, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\extractor\aenetworks.py", line 219, in _real_extract
    playlist = self._call_api(self._RESOURCE, slug, brand, self._FIELDS)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\extractor\aenetworks.py", line 206, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\extractor\common.py", line 1145, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\extractor\common.py", line 1103, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\extractor\adobepass.py", line 1377, in _download_webpage_handle
    return super()._download_webpage_handle(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\extractor\common.py", line 968, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\extractor\common.py", line 917, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\networking\_urllib.py", line 399, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\extractor\common.py", line 904, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\YoutubeDL.py", line 4195, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\networking\common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\networking\_helper.py", line 194, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\networking\common.py", line 359, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\DRMLab-VT1.0\vt-0.1.0-local\.venv\Lib\site-packages\yt_dlp\networking\_urllib.py", line 404, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request